import { useMemo, useState } from 'react';
import { channelPresets, genrePacks, moodPacks, seasonPacks } from './data/presets';
import type { ChannelProfile, GenerationOptions, PlaylistBlueprint, ProviderSettings } from './types';
import { generateBlueprint } from './providers';
import { downloadText, exportCsv, exportJson, exportMarkdown } from './utils/exporters';

const defaultChannel = channelPresets[0];

function clampSongCount(value: number) {
  return Math.min(20, Math.max(10, value));
}

export default function App() {
  const [channels, setChannels] = useState<ChannelProfile[]>(channelPresets);
  const [customChannel, setCustomChannel] = useState('');
  const [selectedChannelId, setSelectedChannelId] = useState(defaultChannel.id);
  const selectedChannel = channels.find(c => c.id === selectedChannelId) || defaultChannel;

  const [provider, setProvider] = useState<ProviderSettings>({ provider: 'local', temperature: 0.8 });
  const [opts, setOpts] = useState<GenerationOptions>({
    channel: selectedChannel,
    projectTitle: 'Autumn to Christmas Playlist Pack',
    songCount: 12,
    lyricLanguage: 'english',
    market: selectedChannel.market,
    audience: selectedChannel.audience,
    genreIds: selectedChannel.preferredGenres,
    moodIds: selectedChannel.preferredMoods,
    seasonId: 'christmas',
    vocalTone: selectedChannel.defaultVocal,
    perspective: 'firstPerson',
    lyricDepth: 'commercial',
    durationTarget: 'under3m30',
    moneyChordMode: 'default',
    customConcept: '',
    avoidWords: ''
  });
  const [blueprint, setBlueprint] = useState<PlaylistBlueprint | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState('');

  const selectedGenres = useMemo(() => genrePacks.filter(g => opts.genreIds.includes(g.id)), [opts.genreIds]);
  const selectedMoods = useMemo(() => moodPacks.filter(m => opts.moodIds.includes(m.id)), [opts.moodIds]);
  const selectedSeason = useMemo(() => seasonPacks.find(s => s.id === opts.seasonId) || seasonPacks[0], [opts.seasonId]);

  function selectChannel(id: string) {
    const channel = channels.find(c => c.id === id) || defaultChannel;
    setSelectedChannelId(id);
    setOpts(prev => ({
      ...prev,
      channel,
      market: channel.market,
      audience: channel.audience,
      lyricLanguage: channel.primaryLanguage,
      genreIds: channel.preferredGenres,
      moodIds: channel.preferredMoods,
      vocalTone: channel.defaultVocal
    }));
  }

  function addConceptChannel() {
    const name = customChannel.trim();
    if (!name) return;
    const id = name.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9가-힣ぁ-んァ-ン一-龯-]/g, '').slice(0, 40) || `channel-${Date.now()}`;
    const channel: ChannelProfile = {
      id,
      name,
      englishName: name,
      market: 'custom',
      primaryLanguage: 'english',
      audience: 'allAges',
      promise: 'custom playlist channel concept generated by creator',
      visualIdentity: 'creator-defined visual identity, consistent colors, readable thumbnail typography',
      defaultVocal: 'clear emotional vocal, polished playlist-friendly delivery',
      preferredGenres: ['adult-contemporary', 'acoustic-pop'],
      preferredMoods: ['warm', 'hopeful'],
      forbiddenCliches: ['famous artist imitation', 'copied song structure'],
      seoKeywords: []
    };
    setChannels(prev => [...prev, channel]);
    setCustomChannel('');
    setSelectedChannelId(id);
    setOpts(prev => ({
      ...prev,
      channel,
      market: channel.market,
      audience: channel.audience,
      lyricLanguage: channel.primaryLanguage,
      genreIds: channel.preferredGenres,
      moodIds: channel.preferredMoods,
      vocalTone: channel.defaultVocal
    }));
  }

  async function onGenerate() {
    setIsGenerating(true);
    setError('');
    try {
      const next = await generateBlueprint({ ...opts, channel: selectedChannel, songCount: clampSongCount(opts.songCount) }, selectedGenres, selectedMoods, selectedSeason, provider);
      setBlueprint(next);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setIsGenerating(false);
    }
  }

  function toggleArray(key: 'genreIds' | 'moodIds', id: string) {
    setOpts(prev => {
      const set = new Set(prev[key]);
      if (set.has(id)) set.delete(id); else set.add(id);
      return { ...prev, [key]: Array.from(set) };
    });
  }

  return (
    <main className="app-shell">
      <header className="hero">
        <div>
          <p className="eyebrow">Suno Weaver Studio v2</p>
          <h1>채널 콘셉트 기반 Suno 프롬프트·가사 생성기</h1>
          <p>현재 시니어 한일 채널부터 향후 키즈, 공부, 여행, 로파이, 계절 채널까지 확장 가능한 모듈식 생성기입니다.</p>
        </div>
      </header>

      <section className="grid two">
        <div className="card">
          <h2>1. 채널 선택/생성</h2>
          <label>채널 프리셋</label>
          <select value={selectedChannelId} onChange={e => selectChannel(e.target.value)}>
            {channels.map(channel => <option key={channel.id} value={channel.id}>{channel.name}</option>)}
          </select>
          <div className="inline">
            <input value={customChannel} onChange={e => setCustomChannel(e.target.value)} placeholder="새 채널명 예: 밤의 재즈책방" />
            <button onClick={addConceptChannel}>채널 추가</button>
          </div>
          <p className="hint">채널을 추가하면 기본 프리셋을 바탕으로 콘셉트별 곡세트를 만들 수 있습니다.</p>
          <textarea value={opts.customConcept} onChange={e => setOpts({ ...opts, customConcept: e.target.value })} placeholder="채널/앨범 콘셉트: 예) 40대 직장인이 퇴근길에 듣는 겨울 도시 팝" />
        </div>

        <div className="card">
          <h2>2. AI 연결 옵션</h2>
          <label>Provider</label>
          <select value={provider.provider} onChange={e => setProvider({ ...provider, provider: e.target.value as ProviderSettings['provider'] })}>
            <option value="local">Local Template / API 없음</option>
            <option value="openai">ChatGPT / OpenAI API</option>
            <option value="anthropic">Claude / Anthropic API</option>
          </select>
          <label>API Key</label>
          <input type="password" value={provider.apiKey || ''} onChange={e => setProvider({ ...provider, apiKey: e.target.value })} placeholder="로컬 테스트용. 공개 배포 시 서버 프록시 권장" />
          <label>Model</label>
          <input value={provider.model || ''} onChange={e => setProvider({ ...provider, model: e.target.value })} placeholder="예: gpt-4.1-mini / claude-3-5-sonnet-latest" />
          <label>Temperature {provider.temperature}</label>
          <input type="range" min="0.2" max="1.2" step="0.1" value={provider.temperature} onChange={e => setProvider({ ...provider, temperature: Number(e.target.value) })} />
        </div>
      </section>

      <section className="card">
        <h2>3. 곡세트 설정</h2>
        <div className="grid three">
          <div><label>프로젝트명</label><input value={opts.projectTitle} onChange={e => setOpts({ ...opts, projectTitle: e.target.value })} /></div>
          <div><label>곡 수 10~20</label><input type="number" min={10} max={20} value={opts.songCount} onChange={e => setOpts({ ...opts, songCount: clampSongCount(Number(e.target.value)) })} /></div>
          <div><label>가사 언어</label><select value={opts.lyricLanguage} onChange={e => setOpts({ ...opts, lyricLanguage: e.target.value as GenerationOptions['lyricLanguage'] })}><option value="english">English</option><option value="korean">Korean</option><option value="japanese">Japanese</option><option value="bilingual">Bilingual</option></select></div>
          <div><label>시즌</label><select value={opts.seasonId} onChange={e => setOpts({ ...opts, seasonId: e.target.value })}>{seasonPacks.map(s => <option key={s.id} value={s.id}>{s.label}</option>)}</select></div>
          <div><label>머니코드</label><select value={opts.moneyChordMode} onChange={e => setOpts({ ...opts, moneyChordMode: e.target.value as GenerationOptions['moneyChordMode'] })}><option value="default">Default I-V-vi-IV</option><option value="emotional">Emotional Lift</option><option value="jazzColor">Jazz Color</option><option value="cityPop">City Pop</option><option value="custom">Custom</option></select></div>
          <div><label>길이 제어</label><select value={opts.durationTarget} onChange={e => setOpts({ ...opts, durationTarget: e.target.value as GenerationOptions['durationTarget'] })}><option value="under3m30">3:10~3:35</option><option value="under4m">4분 이하</option><option value="playlistShort">짧은 플레이리스트용</option></select></div>
        </div>

        <div className="option-block">
          <h3>장르</h3>
          <div className="chips">{genrePacks.map(g => <button key={g.id} className={opts.genreIds.includes(g.id) ? 'chip active' : 'chip'} onClick={() => toggleArray('genreIds', g.id)}>{g.label}</button>)}</div>
        </div>
        <div className="option-block">
          <h3>분위기</h3>
          <div className="chips">{moodPacks.map(m => <button key={m.id} className={opts.moodIds.includes(m.id) ? 'chip active' : 'chip'} onClick={() => toggleArray('moodIds', m.id)}>{m.label}</button>)}</div>
        </div>
        <label>보컬/음색</label>
        <input value={opts.vocalTone} onChange={e => setOpts({ ...opts, vocalTone: e.target.value })} />
        <label>금지어/피해야 할 표현</label>
        <input value={opts.avoidWords} onChange={e => setOpts({ ...opts, avoidWords: e.target.value })} placeholder="예: 특정 가수명, 특정 곡명, 너무 슬픈 표현" />
        <button className="primary" disabled={isGenerating} onClick={onGenerate}>{isGenerating ? '생성 중...' : '10~20곡 일관 생성'}</button>
        {error && <p className="error">{error}</p>}
      </section>

      {blueprint && <section className="card result">
        <div className="result-head">
          <div><h2>{blueprint.projectTitle}</h2><p>{blueprint.oneLineConcept}</p></div>
          <div className="inline buttons">
            <button onClick={() => downloadText('suno-pack.md', exportMarkdown(blueprint), 'text/markdown;charset=utf-8')}>MD 저장</button>
            <button onClick={() => downloadText('suno-pack.json', exportJson(blueprint), 'application/json;charset=utf-8')}>JSON 저장</button>
            <button onClick={() => downloadText('suno-pack.csv', exportCsv(blueprint), 'text/csv;charset=utf-8')}>CSV 저장</button>
          </div>
        </div>
        {blueprint.songs.map(song => <article className="song" key={song.trackNo}>
          <h3>{song.trackNo}. {song.title} <span>{song.qualityScore}/100</span></h3>
          <p><b>상황:</b> {song.listenerSituation} · <b>감정선:</b> {song.emotionArc}</p>
          {song.warnings.length > 0 && <p className="warning">{song.warnings.join(' / ')}</p>}
          <details open>
            <summary>Style Prompt</summary>
            <pre>{song.stylePrompt}</pre>
          </details>
          <details>
            <summary>Lyrics</summary>
            <pre>{song.lyrics}</pre>
          </details>
        </article>)}
      </section>}
    </main>
  );
}
